CREATE TABLE categoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(400) NOT NULL,
    finalidade INTEGER NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editado_em TIMESTAMPTZ,

    CONSTRAINT ck_categoria_finalidade
        CHECK (finalidade IN (1,2,3)) -- 1=Receita, 2=Despesa, 3=Ambas
);