CREATE TABLE transacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id INTEGER NOT NULL,
    categoria_id INTEGER NOT NULL,
    descricao VARCHAR(400),
    valor NUMERIC(15,2) NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editado_em TIMESTAMPTZ,

    -- Chaves estrangeiras
    CONSTRAINT fk_transacao_pessoa
        FOREIGN KEY (pessoa_id)
        REFERENCES pessoa(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_transacao_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categoria(id),

    CONSTRAINT ck_transacao_valor
        CHECK (valor > 0)
);

CREATE INDEX idx_transacao_pessoa
    ON transacao(pessoa_id);

CREATE INDEX idx_transacao_categoria
    ON transacao(categoria_id);