-- ===================================================================
-- SCRIPT DE CRIAÇÃO DO BANCO GASTOS_RESIDENCIAIS
-- Este script apaga as tabelas existentes e recria tudo do zero
-- ===================================================================

-- ================================================================
-- ZERA O BANCO: REMOVE TABELAS ANTERIORES
-- ================================================================
DROP TABLE IF EXISTS transacao CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;
DROP TABLE IF EXISTS pessoa CASCADE;

-- ================================================================
-- TABELA: pessoa
-- ================================================================
CREATE TABLE pessoa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    idade INTEGER NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL,
    editado_em TIMESTAMPTZ,
    
    -- Checks
    CONSTRAINT ck_pessoa_idade
        CHECK (idade BETWEEN 0 AND 130)
);

-- ================================================================
-- TABELA: categoria
-- ================================================================
CREATE TABLE categoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(400) NOT NULL,
    finalidade INTEGER NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL,
    editado_em TIMESTAMPTZ,

    -- Checks
    CONSTRAINT ck_categoria_finalidade
        CHECK (finalidade IN (1,2,3)) -- 1=Receita, 2=Despesa, 3=Ambas
);

-- ================================================================
-- TABELA: transacao
-- ================================================================
CREATE TABLE transacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id INTEGER NOT NULL,
    categoria_id INTEGER NOT NULL,
    descricao VARCHAR(400) NOT NULL,
    valor NUMERIC(15,2) NOT NULL,
    tipo INTEGER NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL,
    editado_em TIMESTAMPTZ,

    -- Chaves estrangeiras
    CONSTRAINT fk_transacao_pessoa
        FOREIGN KEY (pessoa_id)
        REFERENCES pessoa(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_transacao_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categoria(id),

    -- Checks
    CONSTRAINT ck_transacao_valor
        CHECK (valor > 0),

    CONSTRAINT ck_transacao_tipo
        CHECK (tipo IN (1,2))
);

-- ================================================================
-- ÍNDICES para otimizar consultas
-- ================================================================
CREATE INDEX idx_transacao_pessoa ON transacao(pessoa_id);
CREATE INDEX idx_transacao_categoria ON transacao(categoria_id);

-- ===================================================================
-- FIM DO SCRIPT
-- ===================================================================